version: "3.8"

services:
  mysql-server:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=user
      - TZ=Asia/Seoul
    ports:
      - "3306:3306"
  memeber-service:
    image: memeber-service
    ports:
      - "8081:8080"
    depends_on:
      - mysql-server


